# ------------------------------------------------------------------------------
# Training-related hyperparameters and configurations
# ------------------------------------------------------------------------------

# Whether to use the diffusion prior (True) or just retrieval (False)
use_prior: false
blurry_recon: false

# General training params
batch_size: 16
global_batch_size: null
num_epochs: 100
seed: 42

# Learning rate & scheduler
max_lr: 5.0e-05
lr_scheduler_type: "cycle"



# Checkpointing
ckpt_saving: true
ckpt_interval: 3
ckpt_iter: 15000

# Mixup & augmentation
mixup_pct: 0.33
use_image_aug: false

# Blurry reconstruction / contrastive scales
clip_scale: 1.0 # base task
blur_scale: 0.5 # only applies when model.blurry_recon is true
prior_scale: 30 # only applies when model.use_prior is true

# Path to optional multi-subject checkpoint for fine-tuning
multisubject_ckpt: null
